# Generated by Django 4.1.7 on 2023-03-07 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('rfc', models.CharField(max_length=13)),
                ('titular', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('nombre_enlace', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=15, unique=True)),
                ('telefono_enlace', models.CharField(max_length=15, unique=True)),
                ('correo_enlace', models.EmailField(max_length=254, unique=True)),
                ('entidad', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=20)),
                ('colonia', models.CharField(max_length=20)),
                ('codigo_postal', models.IntegerField(max_length=10)),
                ('calle', models.CharField(max_length=30)),
                ('numero', models.PositiveSmallIntegerField(max_length=10)),
                ('estado', models.BooleanField(default=True)),
                ('usuario', models.CharField(max_length=40)),
                ('contraseña', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_pat', models.CharField(max_length=20)),
                ('apellido_mat', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=20)),
                ('matricula', models.CharField(max_length=20)),
                ('correo_pers', models.EmailField(max_length=254)),
                ('correo_inst', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('estado', models.BooleanField(default=True)),
                ('nombre_programa', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=40)),
                ('contraseña', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('contraseña', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id_proceso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaEducativo',
            fields=[
                ('id_programa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=50)),
                ('año', models.PositiveSmallIntegerField()),
                ('vacantes', models.IntegerField()),
                ('modalidad', models.CharField(max_length=50)),
                ('objetivo', models.TextField()),
                ('justificación', models.TextField()),
                ('asesor', models.CharField(max_length=20)),
                ('estado', models.BooleanField(default=True)),
                ('nombre', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='backend.proceso')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoEstudiante',
            fields=[
                ('id_proyectoEst', models.AutoField(primary_key=True, serialize=False)),
                ('id_estudiante', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='backend.estudiante')),
                ('id_proyecto', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='backend.proyecto')),
            ],
        ),
    ]
