# Generated by Django 4.1.7 on 2023-03-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='numero',
            field=models.CharField(max_length=50),
        ),
    ]
